<?php

namespace App\Http\Controllers\V1\Mobile;

use App\Http\Controllers\V1\Controller;
use App\Models\Course;
use App\Models\LogSession;
use App\Models\OrderItem;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;

class TermsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       $data =  '
       <div><h5>Last Updated: August 22, 2020</h5>
                            <p>1.	Introduction</p>
                            <p class="pl-4 pt-0">1.1.	JK Shah Classes Private Limited having its registered office at 4th Floor, Shraddha Old Nagardas Road,  ((hereinafter referred to as “JKSC” or “ us” or “we” or “our” or “Company”) provides classroom based courses, online courses and conducts online classes, live demo, doubt clearing sessions for the students seeking to enrol for such courses (the "Services"), which Services are accessible at online.jkshahclasses.com and any other websites through which JKSC makes the Services available (collectively, the "site" or “platform”) and as applications for mobile, tablet and other smart devices and application program interfaces (collectively, the "Applications").</p>

                            <p class="pl-4 pt-0">1.2.	By accessing or using the Site, Application or Services or by downloading or posting any content from or on the Site, via the Applications, you would be indicating that you have read, and that you understand and agree to be bound by these terms and receive our Services (“Terms of Services” or “Terms”), whether or not you have registered with the Site and/or Application.</p>
                            <p class="pl-4 pt-0">1.3.	Therefore, please read these Terms of service before accessing or using the Site, Application or Services or downloading or posting any content from or on the Site, via the Application or through the Services, carefully as they contain important information regarding your legal rights, remedies and obligations.</p>
                            <p class="pl-4 pt-0">1.4.	We provide the site to you subject to these Terms of Use, which may be updated by us from time to time. By accepting these Terms of Use, you agree to be bound by these Terms and JKSC’s Privacy Policy. If you do not agree to these Terms, you should not access or use the Websites. In addition, when accessing the Websites you shall be subject to any posted guidelines or rules applicable to the Websites, which may be posted and modified from time to time. All such guidelines or rules are hereby incorporated by reference into these Terms.</p>
                            <p class="pl-4 pt-0">1.5.	If you are using the Site, Application or Services then these Terms of Service are binding between you and JKSC.</p>
                            <p>2.	Terms of Use for Site, Application or Services</p>
                            <p class="pl-4 pt-0">2.1.	Accounts
                            You need an account for most activities on our website. Keep your password somewhere safe, because you’re responsible for all activity associated with your account. If you suspect someone else is using your account, let us know by contacting us. You must have reached the age of consent for online services in India to use online.jkshahclasses.com.</p>
                            <p class="pl-4 pt-0">You have complete responsibility for your account and everything that happens on your account, including for any harm or damage (to us or anyone else) caused by someone using your account without your permission. This means you need to be careful with your password. You may not transfer your account to someone else or use someone else’s account. If you contact us to request access to an account, we will not grant you such access unless you can provide us with the information that we need to prove you are the owner of that account. In the event of the death of a user, the account of that user will be closed.
                            </p> <p class="pl-4 pt-0">You may not share your account login credentials with anyone else. You are responsible for what happens with your account and JKSC will not intervene in disputes between students or instructors who have shared account login credentials. You must notify us immediately upon learning that someone else may be using your account without your permission (or if you suspect any other breach of security) by contacting us. We may request some information from you to confirm that you are indeed the owner of your account.</p>
                            <p class="pl-4 pt-0">Students and instructors must be at least 18 years of age to create an account on JKSC and use the Services. If you are younger than 18 but above the required age for consent to use online services where you live, you may not set up an account, but we encourage you to invite a parent or guardian to open an account and help you enroll in courses that are appropriate for you. If you are below this age of consent to use online services, you may not create a JKSC account. If we discover that you have created an account that violates these rules, we will terminate your account.</p>

                            <p class="pl-4 pt-0"> 2.2.	Course Enrollment and Access
                            When you enroll in a course, you get a license from us to view it via the JKSC Services and no other use. Don’t try to transfer or resell courses in any way. We grant you an exclusive access license, except when we must disable the course because of legal or policy reasons.</p>
                            <p class="pl-4 pt-0">As a student, when you enroll in a course, whether it’s a free or paid course, you are getting a license from JKSC to view the course via the JKSC platform and Services, and JKSC is the licensor of record. Courses are licensed, and not sold, to you. This license does not give you any right to resell the course in any manner (including by sharing account information with a purchaser or illegally downloading the course and sharing it on torrent sites).</p>
                            <p class="pl-4 pt-0">In legal, more complete terms, JKSC grants you (as a student) a limited, non-exclusive, non-transferable license to access and view the courses and associated content for which you have paid all required fees, solely for your personal, non-commercial, educational purposes through the Services, in accordance with these Terms and any conditions or restrictions associated with a particular courses or feature of our Services. All other uses are expressly prohibited. You may not reproduce, redistribute, transmit, assign, sell, broadcast, rent, share, lend, modify, adapt, edit, create derivative works of, sublicense, or otherwise transfer or use any course unless we give you explicit permission to do so in a written agreement signed by a JKSC authorized representative. This also applies to content you can access via any of our APIs.</p>

                            <p class="pl-4 pt-0"> We reserve the right to revoke any license to access and use courses at any point in time in the event where we decide or are obligated to disable access to a course due to legal or policy reasons, for example, if the course you enrolled in is the object of a copyright complaint, or if we determine its content violates our Trust & Safety Guidelines.
                            </p> <p class="pl-4 pt-0">Instructors may not grant licenses to the courses to students directly, and any such direct license shall be null and void and a violation of these Terms.</p>
                            <p class="pl-4 pt-0"> 2.3.	Content and Behaviour Rules</p>
                            <p class="pl-4 pt-0">You can only use JKSC for lawful purposes. You’re responsible for all the content that you post on our platform. You should keep the reviews, questions, posts, courses and other content you upload in line with our Trust & Safety Guidelines and the law, and respect the intellectual property rights of others. We can ban your account for repeated or major offenses. If you think someone is infringing your copyright on our platform, let us know.
                            <p class="pl-4 pt-0">You may not access or use the Services or create an account for unlawful purposes. Your use of the Services and behaviour on our platform must comply with applicable local or national laws or regulations of the country. You are solely responsible for the knowledge of and compliance with such laws and regulations that are applicable to you.
                            </p> <p class="pl-4 pt-0"> You may not access our Services if you are from a territory where Indian businesses are prohibited from engaging in business or if you have been designated a Specially Designated National, Denied Person, or Denied Entity by the Indian government. Further, you agree not to upload any content or technology (including information on encryption) whose export is specially controlled under the Export Administration Regulations or other applicable regulations.</p>
                            <p class="pl-4 pt-0">If you are a student, the Services may enable you to ask questions to the instructors of courses you are enrolled in, and to post reviews of courses. For certain courses, the instructor may invite you to submit content as “homework” or tests. Don’t post or submit anything that is not yours.</p>
                            <p class="pl-4 pt-0"> If we are put on notice that your content and behaviour violates the law or the rights of others (for example, if it is established that it violates intellectual property or image rights of others, or is about an illegal activity), if we discover that your content or behaviour violates our Trust & Safety Guidelines, or if we believe your content or behaviour is unlawful, inappropriate, or objectionable (for example if you impersonate someone else), we may remove your access from our platform.</p>
                            <p class="pl-4 pt-0">JKSC has discretion in enforcing these Terms and our Trust & Safety Guidelines. We may terminate or suspend your permission to use our platform and Services or ban your account at any time, with or without notice, for any or no reason, including for any violation of these Terms, if you fail to pay any fees when due, upon the request of law enforcement or government agencies, for extended periods of inactivity, for unexpected technical issues or problems, or if we suspect that you engage in fraudulent or illegal activities, or for any other reason in our sole discretion. Upon any such termination we may delete your account and content, and we may prevent you from further access to the platforms and use of our Services. Your content may still be available on the platforms even if your account is terminated or suspended. You agree that we will have no liability to you or any third party for termination of your account, removal of your content, or blocking of your access to our platforms and services.</p>
                            <p class="pl-4 pt-0"> If one of our instructors has published a course that infringes your copyright or trademark rights, please let us know. Our Instructor Terms require our instructors to follow the law and respect the intellectual property rights of others. For more details on how to file a copyright or trademark infringement claim with us, see our Intellectual Property Policy.</p>
                            <p class="pl-4 pt-0">2.4.	JKSC’s Rights
                            We own the JKSC platform and Services, including the website, present or future apps and services, and things like our logos, API, code, and content created by our employees or vendors. You can’t tamper with those or use them without authorization.</p>
                            <p class="pl-4 pt-0">All right, title, and interest in and to the JKSC platform and Services, including our website, our existing or future applications, our APIs, databases, and the content our employees or partners submit or provide through our Services (but excluding content provided by instructors and students) are and will remain the exclusive property of JKSC and its licensors. Our platforms and services are protected by copyright, trademark, and other laws of both India and foreign countries. Nothing gives you a right to use the JKSC name or any of the JKSC trademarks, logos, domain names, and other distinctive brand features. Any feedback, comments, or suggestions you may provide regarding JKSC or the Services is entirely voluntary and we will be free to use such feedback, comments, or suggestions as we see fit and without any obligation to you.</p>
                            <p class="pl-4 pt-0"> You may not do any of the following while accessing or using the JKSC platform and Services:</p>
                            <ul class="ml-4 pt-0">
                               <li> access, tamper with, or use non-public areas of the platform (including content storage), JKSC’s computer systems, or the technical delivery systems of JKSC’s service providers.</li>
                                <li>	disable, interfere with, or try to circumvent any of the features of the platforms related to security or probe, scan, or test the vulnerability of any of our systems.</li>
                                <li> 	Record, copy, modify, create a derivative work of, reverse engineer, reverse assemble, or otherwise attempt to discover any source code of or content on the JKSC platform or Services.</li>
                                <li> 	access or search or attempt to access or search our platform by any means (automated or otherwise) other than through our currently available search functionalities that are provided via our website, mobile apps, or API (and only pursuant to those API terms and conditions). You may not scrape, spider, use a robot, or use other automated means of any kind to access the Services.</li>
                                <li>	in any way use the Services to send altered, deceptive, or false source-identifying information (such as sending email communications falsely appearing as JKSC); or interfere with, or disrupt, (or attempt to do so), the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the platforms or services, or in any other manner interfering with or creating an undue burden on the Services.</li>

                            </ul><p>2.5.	JKSC’s Rights to Content You Post</p>
                            <p class="pl-4 pt-0"> legal language, by submitting or posting content on or through the platforms, you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display, and distribute your content (including your name and image) in any and all media or distribution methods (existing now or later developed). This includes making your content available to other companies, organizations, or individuals who partner with JKSC for the syndication, broadcast, distribution, or publication of content on other media, as well as using your content for marketing purposes. You also waive any rights of privacy, publicity, or other rights of a similar nature applicable to all these uses, to the extent permissible under applicable law. You represent and warrant that you have all the rights, power, and authority necessary to authorize us to use any content that you submit. You also agree to all such uses of your content with no compensation paid to you.</p>
                            <p>3.	JKSC Intellectual Property Right</p>

                            <p class="pl-4 pt-0">The site, the processes, and their selection and arrangement, including but not limited to all text, graphics, User interfaces, visual interfaces, sounds and music (if any), artwork and computer code on this site is owned and controlled by JKSC and the design, structure, selection, coordination, expression, look and feel and arrangement of such content mentioned hereinabove is protected by copyright, patent and trademark laws, and various other national and international IPR laws and regulations. For clarity, content in the above sentence shall not include User Content.</p>
                            <p class="pl-4 pt-0"> Unless otherwise indicated or anything contained to the contrary, or any proprietary material owned by a third-party and so expressly mentioned, JKSC owns all IPR to and into the trademark “J.K. Shah Classes” and the JKSC site, application or services.</p>
                            <p class="pl-4 pt-0">The mark “JKSC” is the sole property of JKSC. Reproduction in whole or in part of the same is strictly prohibited unless used with an express written permission from JKSC.</p>

                            <p>4.	Electronic Communication</p>
                            <p class="pl-4 pt-0"> When you visit JKSC Website or send email to us, you are communicating with us electronically. By communicating with us, you consent to receive communication from us electronically. We will communicate with you by email or posting notices on JKSC site. You agree that all agreements, notices, disclosures, disclaimers, offers and other communications that are provided to you electronically satisfy any legal requirement that such communication should be in writing.</p>

                            <p> 5.	 Termination of Account</p>
                            <p class="pl-4 pt-0"> JKSC will terminate a Users access to the JKSC Website, if</p>
                            <ul class="ml-4 pt-0">
                                <li>the User is a repeat copyright infringer;</li>
                                <li>the Users breaches any terms of these Terms and Conditions.</li>
                                <li>Violation of any applicable laws;</li>
                                <li>your use of the JKSC Website disrupts our business operations or affects any other party/ User; or</li>
                                <li>you have behaved in a way, which objectively could be regarded as inappropriate or unlawful or illegal or which would bring any claims against JKSC.</li>
                            </ul>
                            <p>  Copyright Infringement</p>
                            <p class="pl-4 pt-0"> JKSC operates a clear copyright policy in relation to any User Content alleged to infringe the copyright of a third party.  As part of JKSCs copyright policy, JKSC will terminate User access to the JKSC Website if a User has been determined to be a repeat infringer. A repeat infringer is a User who has been notified of infringing activity more than twice.</p>
                            <p class="pl-4 pt-0">  If you believe that your work has been copied in a way that constitutes copyright infringement, please refer to the instructions given in the copyright policy on how to make a claim of copyright infringement.</p>

                            <p>Notice of Copyright Infringement:<p>
                            <p class="pl-4 pt-0">Pursuant to provisions of the Indian Copyright Act, 1952 read with the Information Technology Act of 2000, we an intermediary, allow general public to post content on our platform. We have implemented procedures for receiving written notification of claimed infringements on the User Content uploaded on JKSC Website. We have also designated an agent to receive notices of claimed copyright infringement. If you believe in good faith that your copyright has been infringed, you may provide us with a written communication which contains:</p>
                            <ul>
                                <li> 	An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest</li>
                                <li>  	A description of the copyrighted work that you claim has been infringed upon;</li>
                                <li> 	A description of where the material that you claim is infringing is located on the JKSC Website, including the educator name, topic and any other detail identifying the infringing content;</li>
                                <li> 	Your email address, your physical address and telephone number;</li>
                                <li> 	A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and<li>
                                <li> 	A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</li>

                            </ul>
                            <li>Please submit your notice to our Copyright Agent as follows: Email us atlegal@jkshahclasses.com
                                Or contact us by mail at: JKSC ATTN: Legal Department
                            </li>


                            <div class="pl-5 pt-5 pb-5"><p>JK Shah Classes</p>
                                <p> 4th Floor, Shraddha,</p>
                                <p> Near Chinai College,</p>
                                <p> Old Nagardas Road Andheri West, Mumbai 400 069</p>
                            </div>

                           <p> Our policy to deal with Copyright infringements:</p>
                            <p class="pl-4 pt-0"> We follow a 3-strike policy- Three instances brought to our notice that are provided with all required supporting information will lead to the educator getting banned from the JKSC Website. His/her right to any and all compensation or monetary benefit that he/she might be eligible for shall be revoked. The detailed process is as under:</p>

                            <p>Our policy to deal with Copyright infringements:</p>

                            <p> First case of violation- The infringing User Content is taken down and educator is given a warning and is suspended for a week from making any new courses.</p>
                            <p> Second case of violation- The educator is suspended from making any more videos on the JKSC Website for a month and all User Content that amount to copyright violations are brought down immediately.</p>
                            <p> Third violation- The educator is banned from the JKSC Website and will be unable to make any more courses in the future.</p>

                            <p>Confidentiality</p>
                            <p class="pl-4 pt-0">You will not without obtaining prior written consent of JKSC, disclose to third party any Confidential Information (as defined below) that is disclosed to you during the term of your use of the JKSC Website.</p>
                            <p class="pl-4 pt-0">For the purpose of this clause Confidential Information shall include but shall not be limited to employee details, User list, business model, processes, ideas, concepts etc. relating to JKSC or JKSC Website which are not available in the public domain. You acknowledge and agree that the Confidential Information so provided to you shall at all time be the property of JKSC and any breach of the same shall cause irreparable damage to us.</p>

                            <p>Disclaimer</p>
                            <p class="pl-4 pt-0">YOU AGREE THAT YOUR USE OF THE JKSC SITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, JKSC, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS EXCLUDE ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE JKSC WEBSITE AND YOUR USE THEREOF. TO THE FULLEST EXTENT PERMITTED BY LAW, JKSC EXCLUDES ALL WARRANTIES, CONDITIONS, TERMS OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE USER CONTENT OR THE CONTENT OF ANY SITES SO LINKED AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF USER CONTENT OR ANY CONTENT ON JKSC, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE JKSC WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE JKSC WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE JKSC WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY USER CONTENT OR ANY OTHER CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY USER CONTENT OR ANY OTHER CONTENT THAT IS POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE JKSC WEBSITE. JKSC DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY USER CONTENT OR JKSC WEBSITE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE JKSC WEBSITE OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND JKSC WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF USER CONTENT OR SERVICES. AS WITH THE PURCHASE OF A SUBSCRIPTION OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>

                            <p>10. Limitation of Liability</p>
                            <p class="pl-4 pt-0"> TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL JKSC, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, LOSSES OR EXPENSES OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF USER CONTENT OR ANY OTHER CONTENT AVAILABLE AT JKSC, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR JKSC WEBSITES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE JKSC WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR JKSC WEBSITES BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY USER CONTENT OR ANY OTHER CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE JKSC WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT JKSC IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                            </p>
                            <p class="pl-4 pt-0"> WE UNDERSTAND THAT, IN SOME JURISDICTIONS, WARRANTIES, DISCLAIMERS AND CONDITIONS MAY APPLY THAT CANNOT BE LEGALLY EXCLUDED, IF THAT IS TRUE IN YOUR JURISDICTION, THEN TO THE EXTENT PERMITTED BY LAW, JKSC LIMITS ITS LIABILITY FOR ANY CLAIMS UNDER THOSE WARRANTIES OR CONDITIONS TO EITHER SUPPLYING YOU THE JKSC WEBSITES AGAIN.</p>
                            <p class="pl-4 pt-0"> YOU SPECIFICALLY ACKNOWLEDGE THAT JKSC SHALL NOT BE LIABLE FOR USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
                            <p class="pl-4 pt-0"> THE JKSC WEBSITE IS CONTROLLED AND OFFERED BY JKSC FROM ITS FACILITIES IN INDIA. JKSC MAKES NO REPRESENTATIONS THAT THE JKSC WEBSITE IS APPROPRIATE OR AVAILABLE FOR USE IN OTHER LOCATIONS. THOSE WHO ACCESS OR USE THE JKSC WEBSITE FROM OTHER JURISDICTIONS DO SO AT THEIR OWN VOLITION AND ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAW.
                            </p>
                            <p> 11. Indemnity</p>
                            <p class="pl-4 pt-0"> To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless JKSC, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorneys fees)arising from: (i) your use of and access to the JKSC Website;(ii) your violation of any term of these Terms and Conditions; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; (iv) any claim that your User Content caused damage to a third party; or (v) violation of any applicable laws. This defence and indemnification obligation will survive these Terms and Conditions and your use of the JKSC Website.</p>
                            <p> 12. Eligibility to use and Acceptance of the Terms and Conditions</p>
                            <p class="pl-4 pt-0"> You affirm that you are either more than 18 years of age, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms and Conditions, and to abide by and comply with these Terms and Conditions. If you are under 18 years of age, then please talk to your parents or guardian before using the JKSC Website.
                            </p>
                            <p class="pl-4 pt-0">JKSC reserves the right to refuse access to use the JKSC Websites to any Users or to suspend and/or terminate access granted to existing registered Users at any time without according any reasons for doing so.</p>
                            <p class="pl-4 pt-0">We provide these Terms and Conditions with our JKSC Website so that you know what terms apply to your use. You acknowledge that we have given you a reasonable opportunity to review these Terms and Conditions and that you have agreed to them. You agree and acknowledge that your use of the JKSC Website is subject to the most current version of the Terms and Conditions made available on the JKSC Website at the time of such use.</p>
                            <p> 13. Force Majeure</p>
                            <p class="pl-4 pt-0"> JKSC shall not be liable for failure to perform, or the delay in performance of, any of its obligations if, and to the extent that, such failure or delay is caused by events substantially beyond the its control, including but not limited to acts of God, acts of the public enemy or governmental body in its sovereign or contractual capacity, war, terrorism, floods, fire, strikes, epidemics, civil unrest or riots, power outage, and/or unusually severe weather.
                            <p> 14. Information Technology Act</p>
                            <p class="pl-4 pt-0"> These Terms and Conditions are published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms and conditions for access or usage of the JKSC Website.</p>
                            <p class="pl-4 pt-0"> You are advised not to post any information or messages that are, or that may be construed, as being malicious , defamatory, inappropriate, slanderous, pornographic or otherwise sexually oriented or that makes attacks on or the otherwise opines or comments on any individuals or groups of individuals, educational institutions or any other entities whatsoever (whether companies, firms, or any other institutions). You also agree not to post any information to which you do not have copyrights or other appropriate permissions to post in public forum. Your failure to comply with these terms may result in removal of your postings without prior notice to User. The IP address of all posts is recorded to aid in enforcing these conditions.</p>

                            <p> 15. Other Laws</p>
                            <p class="pl-4 pt-0"> Certain laws require to maintain data with respect to the JKSC Website and other personal information in a prescribed format and JKSC will use all the information to the extent required in compliance with the applicable laws and as may be directed or amended from time to time.</p>
                            <p> 16. Governing Law and Jurisdiction</p>
                            <p class="pl-4 pt-0"> The Terms and Conditions are governed by and constructed in accordance with the laws of India, without reference to conflict of laws principles and you irrevocably and unconditionally submit to the exclusive jurisdiction of the courts located in Bangalore, Karnataka, India.</p>
                            <p> 17. Modification, Amendment or Termination</p>
                            <p class="pl-4 pt-0"> JKSC may, in its sole discretion, modify or revise these Terms and Conditions and policies at any time, and you agree to be bound by such modifications or revisions. Your continued use of the JKSC Website post any modification of the Terms and Conditions shall be taken as your consent and acceptance to such modifications. Nothing in these Terms and Conditions shall be deemed to confer any third-party rights or benefits.</p>
                            <p> 18. General</p>
                            <p class="pl-4 pt-0"> If any part of these Terms and Conditions is unlawful, void or unenforceable, that part of will be deemed severable and will not affect the validity and enforceability of any remaining provisions. Any notice required to be given in connection with the JKSC Website shall be in writing and sent to the registered office of JKSC. We do not guarantee continuous, uninterrupted or secure access to the JKSC Website, and operation of the JKSC Website may be interfered by numerous factors outside our control. Headings are for reference purpose only an on no way define, limit, construe or describe the scope or extent of such section. Out failure to act with respect to any breach by you or others does not waive our right to act with respect to subsequent or similar breaches. </p>

                            </div>';

       return $this->jsonResponse('Terms', $data);
    }

    public function privacy()
    {
        $data = '<div class="p-4">
                   <h5>Last Updated: August 22, 2020</h5>
                   <p>This Privacy Policy (“Privacy Policy/Policy”) discloses the privacy practices for JK Shah Classes Private Limited (“JKSC” or “ us” or “we” or “our” or “Company”) with regard to Your (“You/you” or “Your/your”) use of the online platform online.jkshahclasses.com  (“Website”). This Privacy Policy along with Terms of Use describes our practices regarding, including your choices in relation to how we collect, store, use, share and secure your personal information across our Website. It also describes your choices regarding use, access and correction of your personal information and your rights in relation to your personal information and how to contact us or supervisory authorities in the event you have a complaint.</p>
                   <p>By visiting this Website, you agree to be bound by the terms and conditions of this Privacy Policy. Please read this Privacy Policy carefully. By using the Website, you indicate that you understand, agree and consent to this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not use/access this Website.</p>
                   <p> We’ll review this Privacy Policy from time to time to make sure it is up-to-date. If you are just a visitor, then please note that this Privacy Policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this Policy periodically. If you are our registered user, we will notify you before we make changes to this Policy and give you the opportunity to review the revised Policy before you choose to continue using our services.</p>
                    <p> By Personal Data, we mean any information that can either itself identify you as an individual ("Personally Identifying Information ") or that can be connected to you indirectly by linking it to Personally Identifying Information</p>
                    <p> COLLECTION OF INFORMATION</p>
                    <p> As a visitor, you can browse our Website to find out more about our Website. You are not required to provide us with any Personal Data as a visitor. When you visit the Site, we collect and store certain information in order to improve security, analyse trends and administer the Website with a view to assist us in improving customer experience. We use this information to evaluate traffic patterns on our Website so that we can make it more useful to our visitors.</p>
                    <p> We collect your Personal Data when you register with us, when you express an interest in obtaining information about us or our products and services, when you participate in activities on our Website or otherwise contact us.</p>
                    <p> We will only collect your Personal Data if we have a proper reason for doing so, e.g.: to comply with our legal and regulatory obligations; for the performance of our contract with you or to take steps at your request before entering into a contract; for our legitimate interests or those of a third party; or where you have given consent. A legitimate interest is when we have a business or commercial reason to use your information, so long as this is not overridden by your own rights and interests. In some cases, we may also have a legal obligation to collect personal information from you or may otherwise need the personal information to protect your vital interests or those of another person (for example, to prevent payment fraud or confirm your identity.</p>
                    <p>  Our primary goal in collecting your Personal Data and other personal information is to provide you a safe, efficient, smooth and customized experience. This allows us to provide courses, study material, tutorials that most likely meet your needs and to customize our Website to make your experience safer and easier. We also use your Personal Identifiable Information together with other Personally Non-Identifiable Information to help us better understand our users and to improve the content and functionality of our Website. The information we learn from you helps us personalize and continually improve your experience at our Website. We do not voluntarily make this information available to third parties, nor do we use it for any other purpose, except as set out herein.</p>
                    <p>When you visit our Website, as part of a purchase of one of our courses or registering on our Website, we may collect a variety of information that you will voluntarily provide to us via one of our contact forms, via a chat or phone session (Personal Identifying Information), such as:</p>
                    <ul>
                        <li>Contact Information, such as name, email address, display picture, mailing address, phone number, IP address, geographic location, or phone number</li>
                        <li>Information to enable us to check and verify your identity, e.g. your date of birth, mark-sheets, Passport/Aadhar /Voter ID details;</li>
                        <li>Billing Information, such as debit card number, credit card number and billing address;</li>
                        <li>Unique Identifiers, such as username or password;</li>
                        <li>Reviews or ratings, syllabus and course preferences, account settings, (including preferences set in the " Account " section of our Website); and</li>
                        <li>Information provided to us through our service, interaction with our customer service, participation in surveys or marketing promotions.</li>
                    </ul>
<p> We collect information about you and your use of our service, your interactions with us as well as information regarding your computer or other device used to access our service).This information includes your activity on our Website, such as classes, study materials, courses and search queries; details of your interactions with customer service , such as the date , time and reason for contacting us ,transcripts of any chat conversations, and if you call us , your phone number and call recordings; device IDs or other unique identifiers, device and software characteristics (such as type and configuration), connection information, statistics on page views , referring source ( for example, referral URLs ), IP address (which may tell us your general location), browser and standard web server log information, information collected via the use of cookies, web beacons and other technologies.</p>
<p> With the help of back end applications, we aim at providing better services and better interaction with teachers, depending on the beneficiary’s line of interest. We also may ask for this information at other times, such as when you enter contests or other promotions sponsored by us and/or our partners. If you use a feature that requires payment of a fee options like NEFT or Card will appear. In case of payments via credit or debit card, we will redirect you to registered payment gateways such as razorpay, ccavenue, payubiz and other such registered gateways. You may store and save your payment details like card numbers with the gateway. We do not have access to this data. All payment transactions are processed through secure payment gateway providers. We do not store any card information (other than the last 4 digits of your card) in our servers.</p>
<p> When you use one of our paid products, we track the web pages, and information that has been accessed by you, and store it on our servers. This enables us to track items that you have completed, and those that you need to see.</p>
<p> The user full name and his/her display picture can be publicly displayed on the Website. Depending on what profile and what services they are seeking, JKSC can ask for more information relating to address, billing information, certificates, past employment information etc.</p>
<p> JKSC can use technologies such as cookies, clear gifs, log files, and flash cookies for several purposes, including to help understand how you interact with our site and services, in order to provide a better experience.</p>
<h5>USAGE AND RETENTION OF INFORMATION</h5>
<p>We use the personal information we collect, including your Personal Data where it is necessary to deliver the services you have requested, where it is necessary to exercise or comply with legal rights or obligations or for normal business purposes of the kind set out in this Policy.</p>
<p>We will use your personal information to provide, analyse, administer and improve our services, to provide you with a personalized experience on our Website (especially, by offering you services that is best suited for you), to contact you about your account and our services, to provide you customer service, to provide you with personalized marketing and to detect, prevent, mitigate and investigate fraudulent or illegal activities. We further use your personal information to determine your general geographic location, provide localized courses and classes, provide you with customized and personalized study material,  recommendations, determine your Internet service provider , and help us quickly and efficiently respond to inquiries and requests and enforcing our terms (such as determining free trial eligibility) and communicate with you concerning our service (for example by email, push notifications, text messaging ,and online messaging channels), so that we can send you details about new features and content available on the Website, special offers, promotional announcements, surveys, and to assist you with operational requests such as password reset requests.
<h5> COMMUNITY</h5>
<p>JKSC is a community. We offer several features that allow members to connect and communicate in public or semi-public spaces, such as Forums and Teams. Please be sensibile and judge before posting in these community spaces or sharing your personal information with others on JKSC. Be aware that any personal information you submit there can be read, collected, or used by others, or could be used to send you unsolicited messages.</p>
<h5>SHARING AND DISCLOSING PERSONAL INFORMATION</h5>
<p>We use other companies, agents or contractors ("Service Providers") to perform services on our behalf or to assist us with the provision of services to you. We engage Service Providers to provide marketing, advertising, communications, infrastructure and IT services, to personalize and optimize our service, to process credit card transactions or other payment methods, to provide customer service, to collect debts, to analyze and enhance data (including data about users’ interactions with our service), and to process and administer consumer surveys. In the course of providing such services, these Service Providers may have access to your personal or other information.</p>
<p>We do not authorize them to use or disclose your personal information except in connection with providing their services.</p>
<h5> SECURITY</h5>
<p>We shall try to take all precautions to protect the personal information both online and offline. We will try to protect your information using technical and administrative security measures to reduce the risks of loss, misuse, unauthorized access, disclosure and alteration. We have standard SSL certification which basically helps us create a secure connection between our server and user to render any information or action. Some of the safeguards we use are firewalls and data encryption, physical access controls to our data centres and information access authorization controls. Only user passwords are encrypted in 64-bit encryption and stored because generally users use the same password on multiple sites, to prevent any kind of theft, piracy or unauthorised access. If you believe your account has been abused or hacked, please contact us by sending us an email at helpdesk@jkshahclasses.com.</p>
<p> We do not sell, transfer or rent your personal information to third parties for their marketing purposes without your explicit consent and we only use your information as described in the Privacy Policy. We view protection of your privacy as a very important community principle. We understand clearly that you and your Information is one of our most important assets. We store and process your personal information on computers located in India that are protected by physical as well as technological security devices. We use third parties to verify and certify our privacy principles. If you object to your Information being transferred or used in this way, please do not use this Website.</p>
<p>Under no circumstances, we rent, trade, transfer or share your personal information that we have collected with any other company for their marketing purposes without your consent. We reserve the right to communicate your personal information to any third party that makes a legally-compliant request for its disclosure.</p>

<h5> Keeping your Personal Data secure</h5>
<p> We have appropriate security measures to prevent your Personal Data from being accidentally lost or used or accessed unlawfully. Processing your Personal Data will be done only in an authorised manner and subject to a duty of confidentiality. We also have procedures–in-place to deal with any suspected data security breach. We will notify you about any applicable regulator of a suspected data security breach where we are legally required to do so.</p>
<p> Notwithstanding anything contained anywhere in this Agreement; we cannot assure absolute security to your personal data and by entering into or by logging into our website, you explicitly agree not to sue us for any data breach.</p>
<h5>COOKIES</h5>
<p> We transfer cookies, which are small files containing a string of character, to your IP address, giving the browser distinct identification, in order to keep track of the user’s preferences. Furthermore, these files also help in logging-in faster and they act as a mechanism to determine user trends. The data thus retrieved from the user’s IP address, enables us to enhance our offers, including but not limited to more content in areas of greater interest to a majority of users.</p>
<p>Our Website uses "Cookies" to identify the areas of our Website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our Website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our Website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
<h5>THIRD PARTIES AND LINKS</h5>
<p> We may pass your details to other companies in our group. We may also pass your details to our agents and subcontractors to help us with any of our uses of your data set out in our Privacy Policy. For example, we may use third parties to assist us with delivering services to you, to help us to collect payments from you, to analyse data and to provide us with marketing or customer service assistance. We may exchange information with third parties for the purposes of fraud protection and credit risk reduction. We may transfer our databases containing your personal information if we sell our business or part of it. Other than as set out in this Privacy Policy, we shall NOT sell or disclose your personal data to third parties without obtaining your prior consent unless it is necessary for the purposes set out in this Privacy Policy or unless we are required to do so by law. The Site may contain advertising of third parties and links to other sites or frames of other sites. Please be aware that we are not responsible for the privacy practices or content of those third parties or other sites, nor for any third party to whom we transfer your data in accordance with our Privacy Policy.</p>
<p>Our Website may contain links to other websites that are not under our direct control. These websites may have their own policies regarding privacy. We have no control of or responsibility for linked websites and provide these links solely for the convenience and information of our visitors. You accessing such linked Websites shall be at your own risk. These websites are not subject to this Privacy Policy. You should check the privacy policies, if any, of those individual websites to see how the operators of those third-party websites will utilize your personal information. In addition, these websites may contain a link to Websites of our affiliates. The websites of our affiliates are not subject to this Privacy Policy, and you should check their individual privacy policies to see how the operators of such websites will utilize your personal information.</p>
<h5>CONSULTING</h5>
<p>  We use third parties to help us provide services to You including the fulfilment of service, processing of payments, monitoring site activity, conducting surveys, maintaining our database, administering emails, and administering contents, and to provide aggregate, comparative information on the performance of our website to us and a select group.</p>
<h5> CHOICE</h5>
<p>  It is open for you to customize our usage of your personal information to communicate with you, to send you marketing information, how we provide you with customized and relevant advertising, and whether you want to stay signed into your account.</p>
<p>  If you do not wish to receive marketing communications from us, you can unsubscribe from the link in the email you would receive or change your Communication preferences or indicate your communication preferences. You can also reach us via chat, WhatsApp, call or email to block promotional communication to you. Keep in mind, we do not sell or rent your personal information to third parties for their marketing purposes without your explicit consent.</p>
<h5>OWNERSHIP OF RIGHTS</h5>
<p> All rights, including copyright, in this Website are owned by or licensed to us. Any use of this Website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without our permission. You are prohibited from modifying, copying, distributing, transmitting, displaying, printing, publishing, selling, licensing, creating derivative works or using any content available on or through our Website for commercial or public purposes. You may not modify, distribute or re-post something on this Website for any purpose.</p>
<p> The Site contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of JKSC is protected by copyright as a collective work under the applicable copyright laws. JKSC owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as copyright or license to use in the content original to it. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. You may download / print / save copyrighted material for your personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of JKSC is permitted. If copying, redistribution or publication of copyrighted material is expressly permitted by JKSC, then no changes in or deletion of author attribution, trademark legend or copyright notice shall be made.</p>
<p> You acknowledge that you do not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on our Website or a website otherwise owned or operated in conjunction with JKSC shall not be deemed to be in the public domain but rather the exclusive property of JKSC, unless such site is under license from the trademark owner thereof in which case such license is for the exclusive benefit and use of JKSC, unless otherwise stated.</p>
<p> JKSC does not have any express burden or responsibility to provide you with indications, markings or anything else that may aid you in determining whether the material in question is copyrighted or trademarked. You shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. By submitting material to any public area of the Website, you warrant that the owner of such material has expressly granted JKSC the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. You also permit any other end user to access, view, store or reproduce the material for that end users personal use. You hereby grant JKSC, the right to edit, copy, publish and distribute any material made available on the Website by you.</p>
<p> If you come across any abuse or violation of these Terms, please report to helpdesk@jkshahclasses.com.</p>

<h5> CONSENT<h5>
<p> By submitting data to us or our agent or using the Site, you consent to our use of your data in the manner set out in this Privacy Policy.</p>
<h5>CONDITIONS OF USE<h5>
<p> Licensee does not warrant that this website, its servers, or email sent by us or on our behalf are virus free. We will not be liable for any damages of any kind arising from the use of this website, including, but not limited to compensatory, direct, indirect, incidental, punitive, special or consequential damages, loss of data, goodwill, business opportunity, income or profit, loss of or damage to property and claims of third parties.</p>

<h5> GRIEVANCE OFFICER<h5>
<p>  In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:
helpdesk@jkshahclasses.com</p>

<h5> CONSENT TO THIS POLICY<h5>
<p> The Terms of Use Agreement is incorporated herein by reference in its entirety.</p>

<h5>GENERAL</h5>
<p> Modification:
We may at any time modify the Terms of Use of our Website without any prior notification to you. Should you wish to terminate your account due to a modification to the Terms or the Privacy Policy, you may do so email us at helpdesk@jkshahclasses.com.  However, if you continue to use the service you shall be deemed to have agreed to accept and abide by the modified Terms of this Website.</p>

<h5> PRIVILEGED/EXCLUSIVE SERVICE:</h5>
<p> By having a JKSC account, you have explicitly given consent for us to capture images (followed by analysis), camera/mic permissions to make video calls and record the same.</p>
<h5> JKSC MAY DISCLOSE INFORMATION:</h5>
<ul>
    <li> as required by law, such as to comply with a subpoena, or similar legal process;</li>
    <li>to enforce applicable ToU (Terms of Use), including investigation of potential violations thereof;
    <li>when we believe in good faith (doctrine of uberrima fides) that the disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, address security or technical issues or respond to a government request;</li>
    <li>	with our trusted service providers who work on our behalf and do not have an independent use of the information we disclose to them and have agreed to and adhered to the rules set forth in this Policy;</li>
    <li>to protect against imminent harm to the rights, property or safety of the Application/Website or our users or the public as required or permitted by law;</li>
    <li>	with third party service providers in order to personalize the Application/Website/Services/products for a better user experience and to perform behavioural analysis;</li>
</ul>
<h5> Governing Law and Jurisdiction:</h5>
<p> In the event of any dispute arising between the parties with respect to this Agreement, the same shall be referred to the Sole Arbitrator and the arbitration shall be in accordance with Arbitration and Conciliation Act of 1996. The language of arbitration proceeding shall be English. The seat and place of arbitration shall be Bangalore and the decision of the Arbitrator shall be final and binding on both parties herein.</p>
<p> This contract shall be subject to the exclusive jurisdiction of courts in Bangalore, Karnataka, India and shall be governed by the Indian laws.</p>
</div>';

        return $this->jsonResponse('Privacy', $data);
    }

}
